Entrega TP1
AlexisRomero9/Trabajo-Practico-N1-Idea-Proyecto pull request #4
Opened 2024-09-14 10:58 UTC by AlexisRomero9

Se entrega el código desarrollado para el Trabajo Práctico N1, y se actualiza el README.md con un detalle acerca del funcionamiento implementado.

2024-09-16 19:37 UTC, alutenberg requested changes
El trabajo está bastante bien, aunque te marqué varias cosas para revisar.
Quedo atento a tu reentraga.

2024-09-16 19:37 UTC, alutenberg commented on README.md
> +###Desarrollo del código
Acá te quedó mal el espaciado entre ### y Desarrollo y así como está se lee mal.

2024-09-16 19:37 UTC, alutenberg commented on README.md
> +Es un primer acercamiento al modelo final, donde se utilizaron solamente dos entradas analógica, que se simularon con potenciometros, que serán reemplazadas posteriormente con los sensores correspond
1) Te quedó "solamente dos entradas analógica". Te falta la S al final.
2) Te falta la tilde en "potenciometros". 
3) Te falta la tilde en "implemento".
4) Está bien que hayas indicado "El código que implementa el menú es código bloqueante, ya que no sale de la función hasta que se ingrese una opción correcta." pero no sos claro respecto a decir que esto lo vas a solucionar en el TP2, por ejemplo.

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +#define COFFEE_WATER_POURING_TIME 1000 //Tiempo que se debe verter el agua en el café simple (prueba, no es tiempo real)
Acá en el TP1 es admisible que NO sean tiempos reales, pero ya en el TP2 deja de ser aceptable algo así.

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +#define COFFEE '1'
Me parece que esto sería más prolijo implementarlo mediante enum, así:
- https://www.geeksforgeeks.org/enumeration-enum-c/

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +UnbufferedSerial uartUsb(USBTX, USBRX, 115200); //Inicialización de la comunicacion serial
Considero que sería bueno que oportunamente uses format() para explicitar la configuración de la comunicación:
- https://os.mbed.com/docs/mbed-os/v6.16/mbed-os-api-doxy/classmbed_1_1_serial_base.html#a8274461aa9a0611c28c4c6aeae665277

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +void prepareIngredients();
Ok, este tipo de cosas luego serán seguramente estados de una FSM. Me parece bien que ya lo vayas pensando ordenadamente.

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +typedef enum{
Ah! Acá usaste un enum, jeje. Entonces más arriba te indiqué que para tal cosa quizás sería bueno que uses enum y vos quizás ya lo conoces. Bueno, mejor entonces.

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +    cancelButton.mode(PullDown);
Si luego ves que tenes muchas inicializaciones, quizás sea bueno que consideres juntarlas todas en una única función de inicialización.

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +    while (true) {
Me parece super ordenado como lo planteaste acá. Muy bien.

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +void showMenu(char *receivedOption)
Esto parece una especie de máquina de estados, ¿no?
Precisamente en relación con eso, ¿no son excluyentes los diferentes valores? 
En ese caso, ¿no sería más natural la estructura "switch" - "case" para implementar esto?
No digo que lo cambies ahora, porque ya no vale la pena para el TP1, pero sí que lo consideres para el TP2.

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +        delay(1500);
Estos números mágicos de pronto acá en el medio del código no sé si son muy felices.
Quizás sería mejor que pongas todos los delays juntos en algún lugar como definiciones.
Yendo más lejos, no sé si no sería bueno que esots mensajes también estén todos definidos juntos.

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +        uartUsb.write("El cafe está listo\n",2);
¿El "2" qué es?

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +        uartUsb.write( "Elija una opcion\r\n", 18 );
Si esto se hace muy largo, con muchas opciones, quizás sea mejor crear una función para esto.

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +                uartUsb.write("La opcion ingresada es incorrecta, vuelve a intentar\r\n",56);
Quizás sea mejor informar además cuáles son las opciones correctas.

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +        delay(300);
Idem.

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +        delay(300);
Idem

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +    while (potentiometerTemperature < POTENTIOMETER_TEMP_READY && coffeeState == PREPARING)
Está claro que esto es super bloqueante, ¿verdad?
Acá en el TP1 no es problema, pero en el TP2 esto no es admisible.

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +    while (coffeeState == PREPARING && delay_water < COFFEE_WATER_POURING_TIME){
Está claro que esto es super bloqueante, ¿verdad?
Acá en el TP1 no es problema, pero en el TP2 esto no es admisible.

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +    while(coffeeState == PREPARING){
Está claro que esto es super bloqueante, ¿verdad?
Acá en el TP1 no es problema, pero en el TP2 esto no es admisible.

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +            delay(delay_water);
Esto me parece mucho mejor que los "1000" mágicos que aparecen más arriba.
Sugiero nomas poner esto en mayúsculas, como DELAY_WATER, para que quede claro que no es una variable.

2024-09-16 19:37 UTC, alutenberg commented on main.cpp
> +            delay(delay_milk);
Esto me parece mucho mejor que los "1000" mágicos que aparecen más arriba.
Sugiero nomas poner esto en mayúsculas, como DELAY_WATER, para que quede claro que no es una variable.

2024-09-19 17:42 UTC, AlexisRomero9 commented on main.cpp
> +#define COFFEE_WATER_POURING_TIME 1000 //Tiempo que se debe verter el agua en el café simple (prueba, no es tiempo real)
Si, fue para probar la funcionalidad de las entradas analógicas, para el TP2 ya serán los valores pertenecientes a los sensores correspondientes.

2024-09-19 18:04 UTC, AlexisRomero9 commented on main.cpp
> +void showMenu(char *receivedOption)
Habia considerado implementarlo con un switch, pero por un tema de tiempo lo tuve que dejar asi, para el próximo TP lo voy a cambiar.

2024-09-19 18:07 UTC, AlexisRomero9 commented on main.cpp
> +        uartUsb.write("El cafe está listo\n",2);
Un error, era 20.

2024-09-19 18:21 UTC, AlexisRomero9 commented on main.cpp
> +        delay(1500);
No tuve en cuenta tener un enum para los delays, y considero que es buena idea tener los strings que se van a imprimir en un vector, lo voy a tener en cuenta. Tuve problemas para utilizar la función strlen(), no me reconoce la función, nose si me falta algún archivo.

2024-09-19 18:22 UTC, AlexisRomero9 commented on main.cpp
> +        uartUsb.write( "Elija una opcion\r\n", 18 );
Si, sería mas ordenado teniendo una función que se encargue de esto.

2024-09-19 18:25 UTC, AlexisRomero9 commented on main.cpp
> +    while (potentiometerTemperature < POTENTIOMETER_TEMP_READY && coffeeState == PREPARING)
Si, será implementado de otra forma en el TP2.

2024-09-19 18:28 UTC, AlexisRomero9 commented on main.cpp
> +            delay(delay_water);
delay_water es una variable que tiene que ir aumentando a medida que se llena la taza en este caso. En una próxima entrega esto se puede implementar con timers asique podria evitarse tener esta variable

2024-09-20 20:39 UTC, alutenberg commented on README.md
> +###Desarrollo del código
Ok, esto quedó corregido. Lo doy por resuelto.

2024-09-20 20:40 UTC, alutenberg commented on README.md
> +Es un primer acercamiento al modelo final, donde se utilizaron solamente dos entradas analógica, que se simularon con potenciometros, que serán reemplazadas posteriormente con los sensores correspond
Ok, todo esto quedó resuelto.

2024-09-20 20:49 UTC, alutenberg approved these changes
Te doy por aprobado este TP. Quedan algunos pendientes, pero los podes resolver en el TP2.

2024-09-20 20:49 UTC, alutenberg commented on main.cpp
> +UnbufferedSerial uartUsb(USBTX, USBRX, 115200); //Inicialización de la comunicacion serial
Esto me parece que no lo hiciste.

2024-09-20 20:49 UTC, alutenberg commented on main.cpp
> +        delay(1500);
Ok lo relativo a enum y los strings.
Lo de strlen es muy raro que no te ande, no me queda claro qué puede ser. Varios de tus compañeros lo están usando sin problema.

2024-09-20 20:49 UTC, alutenberg commented on main.cpp
> +        uartUsb.write( "Elija una opcion\r\n", 18 );
Ok. Te propongo que implementes ese cambio entonces para el TP2.

2024-09-20 20:49 UTC, alutenberg commented on main.cpp
> +            delay(delay_water);
Ok, excelente.

2024-09-20 21:18 UTC, AlexisRomero9 commented on main.cpp
> +UnbufferedSerial uartUsb(USBTX, USBRX, 115200); //Inicialización de la comunicacion serial
No, no me quedo muy claro como se utilizaba, despues le doy un repaso mas a como se utiliza y lo aplico.

2024-09-20 21:21 UTC, AlexisRomero9 commented on main.cpp
> +        delay(1500);
La parte de strlen lo hable con un compañero ayer y me dijo que el Keil Studio marca como que no conoce la función pero en realidad anda, yo no lo habia probado y pensé que no funcionaba.

2024-09-20 21:22 UTC, merged